server.port: ${PORT:8080}
logging:
  level:
    org:
      atmosphere: warn
spring:
  mustache:
    check-template-location: false
#https://arnoldgalovics.com/feign-fallback/
  cloud:
    openfeign:
      circuit breaker:
        enabled: true
      httpclient:
        connection-timeout: 160000000
        ok-http:
          read-timeout: 160000000

#    openfeign:
#      client:
#        config:
#          feign:
#            url: http://localhost:9000
feign:
  url: http://localhost:9000









# For more information https://vaadin.com/docs/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,ru.soft.webclient
