DELETE FROM exercise;
DELETE FROM workout_round;
DELETE FROM workout_plan;
DELETE FROM workout_session;
DELETE FROM workout_result;
commit;

INSERT INTO exercise (id, title, description, complexity) VALUES
('f386d086-6e5d-11ed-a1eb-0242ac120002','Push-up title','Push-up description',1),
('ff252f6e-6e5d-11ed-a1eb-0242ac120002','Barbell squat title','Barbell squat description',2),
('05bf5a98-6e5e-11ed-a1eb-0242ac120002','Pull-up title','Pull-up description',3);

INSERT INTO workout_round (id, round_schema, title, description) VALUES
('3cd77b78-7a52-11ed-a1eb-0242ac120002',
'{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]}}',
'Warm up round title','Warm up round description'),
('425da3e2-7a52-11ed-a1eb-0242ac120002',
'{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]}}',
'Strength round title','Strength round description'),
('475617e4-7a52-11ed-a1eb-0242ac120002',
'{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]}}',
'Endurance round title','Endurance round description');

INSERT INTO workout_plan (id, workout_schema, title, description) VALUES
('5c83571c-7a52-11ed-a1eb-0242ac120002',
'{"workoutSchema":{"rounds":[{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Warm up","description":"Warm up"},{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Strength","description":"For strength"},{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Endurance","description":"For endurance"}]}}',
'Push-up plan title','Push-up plan description'),
('612ccb86-7a52-11ed-a1eb-0242ac120002',
'{"workoutSchema":{"rounds":[{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Warm up","description":"Warm up"},{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Strength","description":"For strength"},{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Endurance","description":"For endurance"}]}}',
'Barbell squats plan title','Barbell squats plan description'),
('65d1de6a-7a52-11ed-a1eb-0242ac120002',
'{"workoutSchema":{"rounds":[{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Warm up","description":"Warm up"},{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Strength","description":"For strength"},{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Endurance","description":"For endurance"}]}}',
'Pull-up plan title','Pull-up plan description');

INSERT INTO workout_session (id, workout_plan, date_time, note) VALUES
('a34798c2-7ac8-11ed-a1eb-0242ac120002',
'{"workoutPlan":{"title":"Push-up training","description":"Push-up description","workoutSchema":{"rounds":[{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Warm up","description":"Warm up"},{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Strength","description":"For strength"},{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Endurance","description":"For endurance"}]}}}',
'2016-06-22 19:10:25-07','Easy session note'),
('a9323cf6-7ac8-11ed-a1eb-0242ac120002',
'{"workoutPlan":{"title":"Push-up training","description":"Push-up description","workoutSchema":{"rounds":[{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Warm up","description":"Warm up"},{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Strength","description":"For strength"},{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Endurance","description":"For endurance"}]}}}',
'2017-07-10 19:10:25-07','Medium session note'),
('ae9b7996-7ac8-11ed-a1eb-0242ac120002',
'{"workoutPlan":{"title":"Push-up training","description":"Push-up description","workoutSchema":{"rounds":[{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Warm up","description":"Warm up"},{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Strength","description":"For strength"},{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Endurance","description":"For endurance"}]}}}',
'2024-03-20 19:10:25-07','Hard session note');

INSERT INTO workout_result (id, workout_session_id, workout_schema, title, description) VALUES
('6ab39d60-7a52-11ed-a1eb-0242ac120002',
'a34798c2-7ac8-11ed-a1eb-0242ac120002',
'{"workoutSchema":{"rounds":[{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Warm up","description":"Warm up"},{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Strength","description":"For strength"},{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Endurance","description":"For endurance"}]}}',
'Push-up result title','Push-up result description'),
('6f8f8c22-7a52-11ed-a1eb-0242ac120002',
'a9323cf6-7ac8-11ed-a1eb-0242ac120002',
'{"workoutSchema":{"rounds":[{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Warm up","description":"Warm up"},{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Strength","description":"For strength"},{"roundSchema":{"roundStations":[{"exercise":{"title":"Push-up title","description":"Push-up description","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Barbell squat title","description":"Barbell squat description","complexity":2},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"Pull-up title","description":"Pull-up description","complexity":3},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1}]},"title":"Endurance","description":"For endurance"}]}}',
'Barbell squat result title','Barbell squat result description');
