package ru.soft.utils;

public final class JsonTestUtils {

    public static final String WORKOUT_ROUND_SCHEMA_JSON =
            "{\"roundSchema\":{\"roundStations\":[{\"exercise\":{\"title\":\"station title_1\",\"description\":\"station description_1\",\"complexity\":1},\"repetitions\":3,\"weight\":0,\"duration\":100,\"rest\":20,\"order\":1},{\"exercise\":{\"title\":\"station title_2\",\"description\":\"station description_2\",\"complexity\":2},\"repetitions\":6,\"weight\":10,\"duration\":0,\"rest\":10,\"order\":2},{\"exercise\":{\"title\":\"station title_3\",\"description\":\"station description_3\",\"complexity\":3},\"repetitions\":1,\"weight\":5,\"duration\":10,\"rest\":100,\"order\":0}]}}";
    public static final String WORKOUT_SCHEMA_JSON =
            "{\"workoutSchema\":{\"rounds\":[{\"roundSchema\":{\"roundStations\":[{\"exercise\":{\"title\":\"station title_1\",\"description\":\"station description_1\",\"complexity\":1},\"repetitions\":3,\"weight\":0,\"duration\":100,\"rest\":20,\"order\":1},{\"exercise\":{\"title\":\"station title_2\",\"description\":\"station description_2\",\"complexity\":2},\"repetitions\":6,\"weight\":10,\"duration\":0,\"rest\":10,\"order\":2},{\"exercise\":{\"title\":\"station title_3\",\"description\":\"station description_3\",\"complexity\":3},\"repetitions\":1,\"weight\":5,\"duration\":10,\"rest\":100,\"order\":0}]},\"title\":\"round title_1\",\"description\":\"round description_1\"},{\"roundSchema\":{\"roundStations\":[{\"exercise\":{\"title\":\"station title_1\",\"description\":\"station description_1\",\"complexity\":1},\"repetitions\":3,\"weight\":0,\"duration\":100,\"rest\":20,\"order\":1},{\"exercise\":{\"title\":\"station title_2\",\"description\":\"station description_2\",\"complexity\":2},\"repetitions\":6,\"weight\":10,\"duration\":0,\"rest\":10,\"order\":2},{\"exercise\":{\"title\":\"station title_3\",\"description\":\"station description_3\",\"complexity\":3},\"repetitions\":1,\"weight\":5,\"duration\":10,\"rest\":100,\"order\":0}]},\"title\":\"round title_2\",\"description\":\"round description_2\"},{\"roundSchema\":{\"roundStations\":[{\"exercise\":{\"title\":\"station title_1\",\"description\":\"station description_1\",\"complexity\":1},\"repetitions\":3,\"weight\":0,\"duration\":100,\"rest\":20,\"order\":1},{\"exercise\":{\"title\":\"station title_2\",\"description\":\"station description_2\",\"complexity\":2},\"repetitions\":6,\"weight\":10,\"duration\":0,\"rest\":10,\"order\":2},{\"exercise\":{\"title\":\"station title_3\",\"description\":\"station description_3\",\"complexity\":3},\"repetitions\":1,\"weight\":5,\"duration\":10,\"rest\":100,\"order\":0}]},\"title\":\"round title_3\",\"description\":\"round description_3\"}]}}";
    public static final String WORKOUT_PLAN_JSON =
            "{\"workoutPlan\":{\"title\":\"workout title\",\"description\":\"workout description\",\"workoutSchema\":{\"rounds\":[{\"roundSchema\":{\"roundStations\":[{\"exercise\":{\"title\":\"station title_1\",\"description\":\"station description_1\",\"complexity\":1},\"repetitions\":3,\"weight\":0,\"duration\":100,\"rest\":20,\"order\":1},{\"exercise\":{\"title\":\"station title_2\",\"description\":\"station description_2\",\"complexity\":2},\"repetitions\":6,\"weight\":10,\"duration\":0,\"rest\":10,\"order\":2},{\"exercise\":{\"title\":\"station title_3\",\"description\":\"station description_3\",\"complexity\":3},\"repetitions\":1,\"weight\":5,\"duration\":10,\"rest\":100,\"order\":0}]},\"title\":\"round title_1\",\"description\":\"round description_1\"},{\"roundSchema\":{\"roundStations\":[{\"exercise\":{\"title\":\"station title_1\",\"description\":\"station description_1\",\"complexity\":1},\"repetitions\":3,\"weight\":0,\"duration\":100,\"rest\":20,\"order\":1},{\"exercise\":{\"title\":\"station title_2\",\"description\":\"station description_2\",\"complexity\":2},\"repetitions\":6,\"weight\":10,\"duration\":0,\"rest\":10,\"order\":2},{\"exercise\":{\"title\":\"station title_3\",\"description\":\"station description_3\",\"complexity\":3},\"repetitions\":1,\"weight\":5,\"duration\":10,\"rest\":100,\"order\":0}]},\"title\":\"round title_2\",\"description\":\"round description_2\"},{\"roundSchema\":{\"roundStations\":[{\"exercise\":{\"title\":\"station title_1\",\"description\":\"station description_1\",\"complexity\":1},\"repetitions\":3,\"weight\":0,\"duration\":100,\"rest\":20,\"order\":1},{\"exercise\":{\"title\":\"station title_2\",\"description\":\"station description_2\",\"complexity\":2},\"repetitions\":6,\"weight\":10,\"duration\":0,\"rest\":10,\"order\":2},{\"exercise\":{\"title\":\"station title_3\",\"description\":\"station description_3\",\"complexity\":3},\"repetitions\":1,\"weight\":5,\"duration\":10,\"rest\":100,\"order\":0}]},\"title\":\"round title_3\",\"description\":\"round description_3\"}]}}}";

    private JsonTestUtils() {
    }
}
