server.port: 9000

spring:
  application.name: exercise-constructor
  datasource:
    url: jdbc:postgresql://localhost:5430/workoutDB
    username: usr
    password: pwd
    driver-class-name: org.postgresql.Driver
  sql:
    init:
#      data-locations: classpath:db/data.sql
      schema-locations: classpath:db/schema.sql
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/workout-assistant-realm/protocol/openid-connect/certs

springdoc:
  swagger-ui.path: /

logging:
  level:
    root: WARN
    ru.soft: DEBUG
    org.springframework.data: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG