DELETE FROM exercise;
DELETE FROM workout_round;
DELETE FROM workout_plan;
DELETE FROM workout_session;
DELETE FROM workout_result;
commit;

INSERT INTO exercise (id, title, description, complexity) VALUES
('f386d086-6e5d-11ed-a1eb-0242ac120002','Отжимания','Сгибание рук в упоре лежа',1),
('ff252f6e-6e5d-11ed-a1eb-0242ac120002','Приседания','Сгибание ног стоя',2),
('05bf5a98-6e5e-11ed-a1eb-0242ac120002','Подтягивания','Поднимание тела к перекладине',3);

INSERT INTO workout_round (id, round_schema, title, description) VALUES
('3cd77b78-7a52-11ed-a1eb-0242ac120002',
'{"round_schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]}}',
'Разминка','Для развития гибкости'),
('425da3e2-7a52-11ed-a1eb-0242ac120002',
'{"round_schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]}}',
'Силовая','Развиваем силу'),
('475617e4-7a52-11ed-a1eb-0242ac120002',
'{"round_schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]}}',
'Выносливость','Выносливость будет лучше');

INSERT INTO workout_plan (id, workout_schema, title, description) VALUES
('5c83571c-7a52-11ed-a1eb-0242ac120002',
'{"workout_schema":{"rounds":[{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_1","description":"round description_1"},{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_2","description":"round description_2"},{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_3","description":"round description_3"}]}}',
'Жимовая','Жим лежа и подсобки'),
('612ccb86-7a52-11ed-a1eb-0242ac120002',
'{"workout_schema":{"rounds":[{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_1","description":"round description_1"},{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_2","description":"round description_2"},{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_3","description":"round description_3"}]}}',
'День ног','Присед и сопутствующие'),
('65d1de6a-7a52-11ed-a1eb-0242ac120002',
'{"workout_schema":{"rounds":[{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_1","description":"round description_1"},{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_2","description":"round description_2"},{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_3","description":"round description_3"}]}}',
'Бицухи','Много подтягиваний');

INSERT INTO workout_session (id, workout_plan, date_time, note) VALUES
('a34798c2-7ac8-11ed-a1eb-0242ac120002',
'{"workout_plan":{"schema":{"rounds":[{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_1","description":"round description_1"},{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_2","description":"round description_2"},{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_3","description":"round description_3"}]},"title":"workout title","description":"workout description"}}',
'2016-06-22 19:10:25-07','Легкая тренировка'),
('a9323cf6-7ac8-11ed-a1eb-0242ac120002',
'{"workout_plan":{"schema":{"rounds":[{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_1","description":"round description_1"},{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_2","description":"round description_2"},{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_3","description":"round description_3"}]},"title":"workout title","description":"workout description"}}',
'2017-07-10 19:10:25-07','Средняя тренировка'),
('ae9b7996-7ac8-11ed-a1eb-0242ac120002',
'{"workout_plan":{"schema":{"rounds":[{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_1","description":"round description_1"},{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_2","description":"round description_2"},{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_3","description":"round description_3"}]},"title":"workout title","description":"workout description"}}',
'2024-03-20 19:10:25-07','Тяжелая тренировка');

INSERT INTO workout_result (id, workout_session_id, workout_schema, title, description) VALUES
('6ab39d60-7a52-11ed-a1eb-0242ac120002',
'a34798c2-7ac8-11ed-a1eb-0242ac120002',
'{"workout_schema":{"rounds":[{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_1","description":"round description_1"},{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_2","description":"round description_2"},{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_3","description":"round description_3"}]}}',
'Жимовая','Жим лежа и подсобки'),
('6f8f8c22-7a52-11ed-a1eb-0242ac120002',
'a9323cf6-7ac8-11ed-a1eb-0242ac120002',
'{"workout_schema":{"rounds":[{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_1","description":"round description_1"},{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_2","description":"round description_2"},{"schema":{"stations":[{"exercise":{"title":"station title_1","description":"station description_1","complexity":1},"repetitions":3,"weight":0,"duration":100,"rest":20,"order":1},{"exercise":{"title":"station title_2","description":"station description_2","complexity":2},"repetitions":6,"weight":10,"duration":0,"rest":10,"order":2},{"exercise":{"title":"station title_3","description":"station description_3","complexity":3},"repetitions":1,"weight":5,"duration":10,"rest":100,"order":0}]},"title":"round title_3","description":"round description_3"}]}}',
'День ног','Присед и сопутствующие');
